# China customs history

Convert our history files to the format from China Customs:
    
    - 2006 - 2016: G:\OMRrefinery\China\Exportimport\China Customs History\China_Customs_history.csv
    - 1995 - 2015: G:\OMRrefinery\China\Exportimport\China Import History.xls
    
Columns to output:

"Date of data","Commodity code","Commodity","Trading partner code","Trading partner","Quantity","Unit","Supplimentary Quantity","Supplimentary Unit","Renminbi Yuan",

# 2006-2016 (old)

There is a bug in the source file, ignore this.

In [40]:
import pandas as pd

df = pd.read_csv('G:\\OMRrefinery\\China\\Exportimport\\China Customs History\\China_Customs_history.csv', parse_dates=['Period'], dayfirst=True)
df = df[['Country Code', 'Country Name', 'Product Code', 'Unit', 'Period', 'Value']]
df['Date of data'] = df.Period.dt.strftime("%Y%m")
df['Commodity'] = 'Petroleum oils&oils obtained from bituminous minerals, crude'
df['Unit'] = 'Kilograms'
df["Supplimentary Quantity"] = "0"
df["Supplimentary Unit"] = '-'
df["Renminbi Yuan"] = None

df.rename(columns={"Product Code": "Commodity code", 
                    "Country Code": "Trading partner code", 
                    "Country Name": "Trading partner",
                    "Value": "Quantity"}, inplace=True)

df = df[["Date of data","Commodity code","Commodity","Trading partner code","Trading partner","Quantity","Unit","Supplimentary Quantity","Supplimentary Unit","Renminbi Yuan"]].sort_values(by=['Date of data', 'Trading partner code'])
df.head()

,Date of data,Commodity code,Commodity,Trading partner code,Trading partner,Quantity,Unit,Supplimentary Quantity,Supplimentary Unit,Renminbi Yuan
1791,200601,27090000,Petroleum oils&oils obtained from bituminous m...,105,Brunei,81965000,Kilograms,0,-,None
2653,200601,27090000,Petroleum oils&oils obtained from bituminous m...,106,Myanmar,0,Kilograms,0,-,None
10337,200601,27090000,Petroleum oils&oils obtained from bituminous m...,109,North Korea,51130000,Kilograms,0,-,None
2767,200601,27090000,Petroleum oils&oils obtained from bituminous m...,110,Hong Kong,0,Kilograms,0,-,None
10932,200601,27090000,Petroleum oils&oils obtained from bituminous m...,110,Hong Kong,0,Kilograms,0,-,None

In [41]:
df.to_csv('cn_customs_crudeoil_imp_2006_2016.csv', index=False)

# 2006 - 2016 (new)

In [75]:
import pandas as pd
df = pd.read_excel('G:\\OMRrefinery\\China\\Exportimport\\China Customs History\\China_Customs_history_2006-2016.xlsx', 'Sheet1')\
       .replace(0,None)\
       .melt(id_vars=['Code_cn', 'code', 'country'], var_name='period', value_name='value')\
       .dropna(subset=['value'])
# "Date of data","Commodity code","Commodity","Trading partner code","Trading partner","Quantity","Unit","Supplimentary Quantity","Supplimentary Unit","Renminbi Yuan",
df = df.rename(columns={'Code_cn': 'Trading partner code',
           'country': 'Trading partner',
           'value': 'Quantity'})\
       .assign(**{'Date of data' : df.period.dt.strftime("%Y%m"),
                  'Commodity code': '27090000',
                  'Commodity': 'Petroleum oils&oils obtained from bituminous minerals, crude',
                  'Unit': 'Kilograms',
                  'Supplimentary Quantity': '0',
                  'Supplimentary Unit': '-',
                  'Renminbi Yuan': None})\
       .drop(columns=['code', 'period'])
df = df[["Date of data","Commodity code","Commodity","Trading partner code","Trading partner","Quantity","Unit","Supplimentary Quantity","Supplimentary Unit","Renminbi Yuan"]]
df.to_csv('cn_customs_crudeoil_imp_2006_2016.csv', index=False)

,Date of data,Commodity code,Commodity,Trading partner code,Trading partner,Quantity,Unit,Supplimentary Quantity,Supplimentary Unit,Renminbi Yuan
0,200601,27090000,Petroleum oils&oils obtained from bituminous m...,126,Oman,1365277.0,Kilograms,0,-,None
1,200601,27090000,Petroleum oils&oils obtained from bituminous m...,113,Iran,1891841.0,Kilograms,0,-,None
2,200601,27090000,Petroleum oils&oils obtained from bituminous m...,131,Saudi Arabia,1604366.0,Kilograms,0,-,None
3,200601,27090000,Petroleum oils&oils obtained from bituminous m...,139,Yemen,353846.0,Kilograms,0,-,None
4,200601,27090000,Petroleum oils&oils obtained from bituminous m...,114,Iraq,353846.0,Kilograms,0,-,None
5,200601,27090000,Petroleum oils&oils obtained from bituminous m...,130,Qatar,135634.0,Kilograms,0,-,None
6,200601,27090000,Petroleum oils&oils obtained from bituminous m...,138,UAE,569072.0,Kilograms,0,-,None
7,200601,27090000,Petroleum oils&oils obtained from bituminous m...,118,Kuwait,139773.0,Kilograms,0,-,None
8,200601,27090000,Petroleum oils&oils obtained from bituminous m...,135,Syria,139773.0,Kilograms,0,-,None
9,200601,27090000,Petroleum oils&oils obtained from bituminous m...,112,Indonesia,486129.0,Kilograms,0,-,None
10,200601,27090000,Petroleum oils&oils obtained from bituminous m...,141,Vietnam,136191.0,Kilograms,0,-,None
11,200601,27090000,Petroleum oils&oils obtained from bituminous m...,601,Australia,81980.0,Kilograms,0,-,None
12,200601,27090000,Petroleum oils&oils obtained from bituminous m...,122,Malaysia,34531.0,Kilograms,0,-,None
13,200601,27090000,Petroleum oils&oils obtained from bituminous m...,105,Brunei,81965.0,Kilograms,0,-,None
14,200601,27090000,Petroleum oils&oils obtained from bituminous m...,136,Thailand,151893.0,Kilograms,0,-,None
15,200601,27090000,Petroleum oils&oils obtained from bituminous m...,611,Papua New Guinea,151893.0,Kilograms,0,-,None
16,200601,27090000,Petroleum oils&oils obtained from bituminous m...,124,Mongolia,4924.0,Kilograms,0,-,None
17,200601,27090000,Petroleum oils&oils obtained from bituminous m...,127,Pakistan,4924.0,Kilograms,0,-,None
18,200601,27090000,Petroleum oils&oils obtained from bituminous m...,132,Singapore,4924.0,Kilograms,0,-,None
19,200601,27090000,Petroleum oils&oils obtained from bituminous m...,116,Japan,4924.0,Kilograms,0,-,None
20,200601,27090000,Petroleum oils&oils obtained from bituminous m...,106,Myanmar,4924.0,Kilograms,0,-,None
21,200601,27090000,Petroleum oils&oils obtained from bituminous m...,110,Hong Kong,4924.0,Kilograms,0,-,None
22,200601,27090000,Petroleum oils&oils obtained from bituminous m...,143,"Taiwan, China",4924.0,Kilograms,0,-,None
23,200601,27090000,Petroleum oils&oils obtained from bituminous m...,142,China,4924.0,Kilograms,0,-,None
24,200601,27090000,Petroleum oils&oils obtained from bituminous m...,609,New Zealand,4924.0,Kilograms,0,-,None
25,200601,27090000,Petroleum oils&oils obtained from bituminous m...,111,India,4924.0,Kilograms,0,-,None
26,200601,27090000,Petroleum oils&oils obtained from bituminous m...,133,South Korea,4924.0,Kilograms,0,-,None
27,200601,27090000,Petroleum oils&oils obtained from bituminous m...,129,Philippines,4924.0,Kilograms,0,-,None
28,200601,27090000,Petroleum oils&oils obtained from bituminous m...,202,Angola,1553668.0,Kilograms,0,-,None
29,200601,27090000,Petroleum oils&oils obtained from bituminous m...,218,Gabon,131658.0,Kilograms,0,-,None
...,...,...,...,...,...,...,...,...,...,...
10615,201612,27090000,Petroleum oils&oils obtained from bituminous m...,114,Iraq,3132628.0,Kilograms,0,-,None
10616,201612,27090000,Petroleum oils&oils obtained from bituminous m...,130,Qatar,65751.0,Kilograms,0,-,None
10617,201612,27090000,Petroleum oils&oils obtained from bituminous m...,138,UAE,1687388.0,Kilograms,0,-,None
10618,201612,27090000,Petroleum oils&oils obtained from bituminous m...,118,Kuwait,1483663.0,Kilograms,0,-,None
10621,201612,27090000,Petroleum oils&oils obtained from bituminous m...,141,Vietnam,223611.0,Kilograms,0,-,None
10622,201612,27090000,Petroleum oils&oils obtained from bituminous m...,601,Australia,288799.0,Kilograms,0,-,None
10623,201612,27090000,Petroleum oils&oils obtained from bituminous m...,122,Malaysia,907074.0,Kilograms,0,-,None
10624,201612,27090000,Petroleum oils&oils obtained from bituminous m...,105,Brunei,75659.0,Kilograms,0,-,None
10625,201612,27090000,Petroleum oils&oils obtained from bituminous m...,136,Thailand,42725.0,Kilograms,0,-,None
10627,201612,27090000,Petroleum oils&oils obtained from bituminous m...,124,Mongolia,89558.0,Kilograms,0,-,None
10639,201612,27090000,Petroleum oils&oils obtained from bituminous m...,202,Angola,3397961.0,Kilograms,0,-,None
10640,201612,27090000,Petroleum oils&oils obtained from bituminous m...,218,Gabon,437706.0,Kilograms,0,-,None
10641,201612,27090000,Petroleum oils&oils obtained from bituminous m...,246,Sudan,94739.0,Kilograms,0,-,None
10642,201612,27090000,Petroleum oils&oils obtained from bituminous m...,216,Equatorial Guinea,137441.0,Kilograms,0,-,None
10644,201612,27090000,Petroleum oils&oils obtained from bituminous m...,226,Libya,376710.0,Kilograms,0,-,None
10645,201612,27090000,Petroleum oils&oils obtained from bituminous m...,215,Egypt,136545.0,Kilograms,0,-,None
10646,201612,27090000,Petroleum oils&oils obtained from bituminous m...,213,Congo,600035.0,Kilograms,0,-,None
10649,201612,27090000,Petroleum oils&oils obtained from bituminous m...,220,Ghana,258062.0,Kilograms,0,-,None
10650,201612,27090000,Petroleum oils&oils obtained from bituminous m...,260,South Sudan,450104.0,Kilograms,0,-,None
10661,201612,27090000,Petroleum oils&oils obtained from bituminous m...,145,Kazakhstan,203310.0,Kilograms,0,-,None
10662,201612,27090000,Petroleum oils&oils obtained from bituminous m...,344,Russia,5040687.0,Kilograms,0,-,None
10663,201612,27090000,Petroleum oils&oils obtained from bituminous m...,339,Azerbaijan,265523.0,Kilograms,0,-,None
10668,201612,27090000,Petroleum oils&oils obtained from bituminous m...,326,Norway,138349.0,Kilograms,0,-,None
10669,201612,27090000,Petroleum oils&oils obtained from bituminous m...,303,United Kingdom,937780.0,Kilograms,0,-,None
10678,201612,27090000,Petroleum oils&oils obtained from bituminous m...,429,Mexico,73878.0,Kilograms,0,-,None
10679,201612,27090000,Petroleum oils&oils obtained from bituminous m...,410,Brazil,2552761.0,Kilograms,0,-,None
10680,201612,27090000,Petroleum oils&oils obtained from bituminous m...,402,Argentina,296705.0,Kilograms,0,-,None
10684,201612,27090000,Petroleum oils&oils obtained from bituminous m...,419,Ecuador,307034.0,Kilograms,0,-,None
10685,201612,27090000,Petroleum oils&oils obtained from bituminous m...,445,Venezuela,1749681.0,Kilograms,0,-,None
10686,201612,27090000,Petroleum oils&oils obtained from bituminous m...,413,Columbia,628335.0,Kilograms,0,-,None

# 1995 - 2005

In [149]:
# 1995 - 2005
country_mapping = {'Russia': 'Russian Federation',
                   'Saudi': 'Saudi Arabia',
                   'Congo': 'Republic of Congo',
                   'Libya': 'Libyan Arab Jamahiriya',
                   'UAE': 'United Arab Emirates',
                   'Democratic Republic of the Congo': 'Congo (Gold)',
                   'South Sudan': 'Republic of South Sudan',
                   'US': 'United States',
                   'UK': 'United Kingdom'}


df = pd.read_excel('G:\OMRrefinery\China\Exportimport\China Import History.xls', 'Oil Imports').query('Period.dt.year < 2006')
df = df.assign(**{'Date of data' : df.Period.dt.strftime("%Y%m"),
                'Commodity code': '27090000',
                'Commodity': 'Petroleum oils&oils obtained from bituminous minerals, crude',
                'Unit': 'Kilograms',
                'Supplimentary Quantity': '0',
                'Supplimentary Unit': '-',
                'Renminbi Yuan': None})\
       .rename(columns={"Product Code": "Commodity code",
                        "Attribute": "Trading partner",
                    "Country Code": "Trading partner code",
                    "Value": "Quantity"})
df['Trading partner'] = df['Trading partner'].apply(lambda x : country_mapping[x] if x in country_mapping else x)

In [150]:
df.head()

,Period,Trading partner,Quantity,Date of data,Commodity code,Commodity,Unit,Supplimentary Quantity,Supplimentary Unit,Renminbi Yuan
0,1995-01-31,Oman,139218345,199501,27090000,Petroleum oils&oils obtained from bituminous m...,Kilograms,0,-,None
1,1995-01-31,Indonesia,149962998,199501,27090000,Petroleum oils&oils obtained from bituminous m...,Kilograms,0,-,None
2,1995-02-28,Indonesia,209311244,199502,27090000,Petroleum oils&oils obtained from bituminous m...,Kilograms,0,-,None
3,1995-03-31,Angola,250294188,199503,27090000,Petroleum oils&oils obtained from bituminous m...,Kilograms,0,-,None
4,1995-03-31,Oman,414925988,199503,27090000,Petroleum oils&oils obtained from bituminous m...,Kilograms,0,-,None

In [151]:
mapping = pd.read_excel('cn_customs_mappings.xlsx', 'COUNTRIES')

In [152]:
merged = df.merge(mapping, left_on = 'Trading partner', right_on = 'country_name_en', how='left', indicator='join_side').rename(columns={'country_code': 'Trading partner code'})
if len(merged.query('join_side == "left_only"')[['Trading partner']].drop_duplicates()) > 0:
        raise ValueError("still wrong names")
merged = merged[["Date of data","Commodity code","Commodity","Trading partner code","Trading partner","Quantity","Unit","Supplimentary Quantity","Supplimentary Unit","Renminbi Yuan"]].sort_values(by=['Date of data', 'Trading partner code'])
merged.head()

,Date of data,Commodity code,Commodity,Trading partner code,Trading partner,Quantity,Unit,Supplimentary Quantity,Supplimentary Unit,Renminbi Yuan
1,199501,27090000,Petroleum oils&oils obtained from bituminous m...,112,Indonesia,149962998,Kilograms,0,-,None
0,199501,27090000,Petroleum oils&oils obtained from bituminous m...,126,Oman,139218345,Kilograms,0,-,None
2,199502,27090000,Petroleum oils&oils obtained from bituminous m...,112,Indonesia,209311244,Kilograms,0,-,None
5,199503,27090000,Petroleum oils&oils obtained from bituminous m...,112,Indonesia,796453975,Kilograms,0,-,None
4,199503,27090000,Petroleum oils&oils obtained from bituminous m...,126,Oman,414925988,Kilograms,0,-,None

In [153]:
merged['Date of data'].drop_duplicates()

1       199501
2       199502
5       199503
11      199504
18      199505
29      199506
34      199507
40      199508
47      199509
53      199510
57      199511
64      199512
70      199701
77      199702
82      199703
89      199704
96      199705
103     199706
111     199707
120     199708
130     199709
139     199710
147     199711
158     199712
167     199801
178     199802
190     199803
199     199804
205     199805
214     199806
         ...
1025    200307
1039    200308
1055    200309
1073    200310
1092    200311
1107    200312
1123    200401
1138    200402
1154    200403
1171    200404
1192    200405
1211    200406
1229    200407
1245    200408
1264    200409
1282    200410
1299    200411
1316    200412
1332    200501
1348    200502
1365    200503
1385    200504
1406    200505
1423    200506
1441    200507
1461    200508
1479    200509
1500    200510
1519    200511
1536    200512
Name: Date of data, Length: 120, dtype: object

In [154]:
merged.to_csv('cn_customs_crudeoil_imp_1995_2005.csv', index=False)

# Load history into External-DB

In [72]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [73]:
import scraper.jobs.cn_customs.crude_imports_job as crude_imports_job
import logging
crude_imports_job.logger.level = logging.DEBUG

cn = crude_imports_job.CrudeImportsJob(full_load=True)

cn.run()

WARNING:scraper.jobs.cn_customs.crude_imports_job:Download method not implemented
WARNING:scraper.jobs.cn_customs.crude_imports_job:Download method not implemented
WARNING:scraper.jobs.cn_customs.crude_imports_job:Download method not implemented
WARNING:scraper.jobs.cn_customs.crude_imports_job:Download method not implemented
WARNING:scraper.jobs.cn_customs.crude_imports_job:Download method not implemented
WARNING:scraper.jobs.cn_customs.crude_imports_job:Download method not implemented
WARNING:scraper.jobs.cn_customs.crude_imports_job:Download method not implemented
WARNING:scraper.jobs.cn_customs.crude_imports_job:Download method not implemented
WARNING:scraper.jobs.cn_customs.crude_imports_job:Download method not implemented
c:\users\rosa_l\pycharmprojects\scrapper\venv\lib\site-packages\pandas\core\indexing.py:1472: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

In [17]:
cn.transform()

c:\users\rosa_l\pycharmprojects\scrapper\venv\lib\site-packages\pandas\core\indexing.py:1472: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

In [30]:
cn.data[1:10]

[{'source': 'cn_customs_crudeoil_imp_2006',
  'period': 'JAN2006',
  'to_area': 'MYANMAR',
  'unit': 'KT',
  'value': 0.0,
  'provider': 'CN_CUSTOMS',
  'area': 'CHINA',
  'product': 'CRUDEOIL',
  'frequency': 'Monthly',
  'flow': 'IMPORTS',
  'original': True},
 {'source': 'cn_customs_crudeoil_imp_2006',
  'period': 'JAN2006',
  'to_area': 'KOREADPR',
  'unit': 'KT',
  'value': 51.13,
  'provider': 'CN_CUSTOMS',
  'area': 'CHINA',
  'product': 'CRUDEOIL',
  'frequency': 'Monthly',
  'flow': 'IMPORTS',
  'original': True},
 {'source': 'cn_customs_crudeoil_imp_2006',
  'period': 'JAN2006',
  'to_area': 'HONGKONG',
  'unit': 'KT',
  'value': 0.0,
  'provider': 'CN_CUSTOMS',
  'area': 'CHINA',
  'product': 'CRUDEOIL',
  'frequency': 'Monthly',
  'flow': 'IMPORTS',
  'original': True},
 {'source': 'cn_customs_crudeoil_imp_2006',
  'period': 'JAN2006',
  'to_area': 'INDIA',
  'unit': 'KT',
  'value': 0.0,
  'provider': 'CN_CUSTOMS',
  'area': 'CHINA',
  'product': 'CRUDEOIL',
  'frequency': 'Monthly',
  'flow': 'IMPORTS',
  'original': True},
 {'source': 'cn_customs_crudeoil_imp_2006',
  'period': 'JAN2006',
  'to_area': 'INDONESIA',
  'unit': 'KT',
  'value': 486.129,
  'provider': 'CN_CUSTOMS',
  'area': 'CHINA',
  'product': 'CRUDEOIL',
  'frequency': 'Monthly',
  'flow': 'IMPORTS',
  'original': True},
 {'source': 'cn_customs_crudeoil_imp_2006',
  'period': 'JAN2006',
  'to_area': 'INDONESIA',
  'unit': 'KT',
  'value': 34.531,
  'provider': 'CN_CUSTOMS',
  'area': 'CHINA',
  'product': 'CRUDEOIL',
  'frequency': 'Monthly',
  'flow': 'IMPORTS',
  'original': True},
 {'source': 'cn_customs_crudeoil_imp_2006',
  'period': 'JAN2006',
  'to_area': 'INDONESIA',
  'unit': 'KT',
  'value': 0.0,
  'provider': 'CN_CUSTOMS',
  'area': 'CHINA',
  'product': 'CRUDEOIL',
  'frequency': 'Monthly',
  'flow': 'IMPORTS',
  'original': True},
 {'source': 'cn_customs_crudeoil_imp_2006',
  'period': 'JAN2006',
  'to_area': 'IRAN',
  'unit': 'KT',
  'value': 1891.841,
  'provider': 'CN_CUSTOMS',
  'area': 'CHINA',
  'product': 'CRUDEOIL',
  'frequency': 'Monthly',
  'flow': 'IMPORTS',
  'original': True},
 {'source': 'cn_customs_crudeoil_imp_2006',
  'period': 'JAN2006',
  'to_area': 'IRAN',
  'unit': 'KT',
  'value': 0.0,
  'provider': 'CN_CUSTOMS',
  'area': 'CHINA',
  'product': 'CRUDEOIL',
  'frequency': 'Monthly',
  'flow': 'IMPORTS',
  'original': True}]

In [37]:
import pandas as pd
df = pd.DataFrame(cn.data)

In [38]:
#df.dropna(axis='index', subset=['value'],inplace=True)
df.isnull().values.any()

False

In [43]:
df

,area,flow,frequency,original,period,product,provider,source,to_area,unit,value
0,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,BRUNEI,KT,81.965000
1,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,MYANMAR,KT,0.000000
2,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,KOREADPR,KT,51.130000
3,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,HONGKONG,KT,0.000000
4,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,INDIA,KT,0.000000
5,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,INDONESIA,KT,486.129000
6,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,INDONESIA,KT,34.531000
7,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,INDONESIA,KT,0.000000
8,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,IRAN,KT,1891.841000
9,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,IRAN,KT,0.000000
10,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,IRAQ,KT,0.000000
11,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,ISRAEL,KT,0.000000
12,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,JAPAN,KT,0.000000
13,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,KUWAIT,KT,135.634000
14,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,KUWAIT,KT,139.773000
15,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,MALAYSIA,KT,0.000000
16,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,MONGOLIA,KT,4.924000
17,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,OMAN,KT,1365.277000
18,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,OMAN,KT,0.000000
19,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,PAKISTAN,KT,0.000000
20,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,PHILIPPINE,KT,0.000000
21,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,SAUDIARABI,KT,1604.366000
22,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,SINGAPORE,KT,0.000000
23,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,SINGAPORE,KT,78.868000
24,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,KOREA,KT,0.000000
25,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,KOREA,KT,257.709000
26,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,SYRIA,KT,0.000000
27,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,THAILAND,KT,151.893000
28,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,THAILAND,KT,0.000000
29,CHINA,IMPORTS,Monthly,True,JAN2006,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_2006,TURKEY,KT,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
14947,CHINA,IMPORTS,Monthly,True,NOV2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,THAILAND,KT,73.607720
14948,CHINA,IMPORTS,Monthly,True,NOV2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,UAE,KT,131.891000
14949,CHINA,IMPORTS,Monthly,True,NOV2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,VIETNAM,KT,311.278182
14950,CHINA,IMPORTS,Monthly,True,NOV2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,KAZAKHSTAN,KT,71.204441
14951,CHINA,IMPORTS,Monthly,True,NOV2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,ALGERIA,KT,173.350028
14952,CHINA,IMPORTS,Monthly,True,NOV2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,ANGOLA,KT,1667.548102
14953,CHINA,IMPORTS,Monthly,True,NOV2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,CONGO,KT,763.598424
14954,CHINA,IMPORTS,Monthly,True,NOV2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,EQGUINEA,KT,424.397079
14955,CHINA,IMPORTS,Monthly,True,NOV2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,LIBYA,KT,70.056000
14956,CHINA,IMPORTS,Monthly,True,NOV2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,SUDAN,KT,393.389670
14957,CHINA,IMPORTS,Monthly,True,NOV2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,RUSSIA,KT,1320.764460
14958,CHINA,IMPORTS,Monthly,True,NOV2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,BRAZIL,KT,140.000000
14959,CHINA,IMPORTS,Monthly,True,NOV2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,VENEZUELA,KT,137.974970
14960,CHINA,IMPORTS,Monthly,True,DEC2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,INDONESIA,KT,304.569243
14961,CHINA,IMPORTS,Monthly,True,DEC2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,IRAN,KT,415.524040
14962,CHINA,IMPORTS,Monthly,True,DEC2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,MONGOLIA,KT,0.857840
14963,CHINA,IMPORTS,Monthly,True,DEC2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,OMAN,KT,1009.865666
14964,CHINA,IMPORTS,Monthly,True,DEC2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,SAUDIARABI,KT,2164.955612
14965,CHINA,IMPORTS,Monthly,True,DEC2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,THAILAND,KT,55.235677
14966,CHINA,IMPORTS,Monthly,True,DEC2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,UAE,KT,258.713609
14967,CHINA,IMPORTS,Monthly,True,DEC2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,VIETNAM,KT,187.167383
14968,CHINA,IMPORTS,Monthly,True,DEC2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,KAZAKHSTAN,KT,138.418755
14969,CHINA,IMPORTS,Monthly,True,DEC2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,ANGOLA,KT,2059.892784
14970,CHINA,IMPORTS,Monthly,True,DEC2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,CONGO,KT,297.718921
14971,CHINA,IMPORTS,Monthly,True,DEC2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,EQGUINEA,KT,412.281100
14972,CHINA,IMPORTS,Monthly,True,DEC2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,LIBYA,KT,193.493590
14973,CHINA,IMPORTS,Monthly,True,DEC2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,SUDAN,KT,412.379851
14974,CHINA,IMPORTS,Monthly,True,DEC2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,RUSSIA,KT,1231.030485
14975,CHINA,IMPORTS,Monthly,True,DEC2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,BRAZIL,KT,112.232040
14976,CHINA,IMPORTS,Monthly,True,DEC2005,CRUDEOIL,CN_CUSTOMS,cn_customs_crudeoil_imp_1995,VENEZUELA,KT,736.047020

In [23]:
cn.sources

['BaseSource(c...imp_2006.csv)', 'BaseSource(c...imp_1995.csv)']

In [13]:
df.index

Index([], dtype='object')

In [3]:
import pandas as pd
data = pd.DataFrame([{'country': 'AUSTRALI'}])
data.isin(['AUSTRALIA', 'BRAZIL'])

   country
0    False

In [7]:
len(data.index)

1